name: Android CI

on:
  push:
    branches: 
       - master
       - develop
  pull_request:
    branches:
       - master
       - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create LOCAL_PROPERTIES
      run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle.caches
          ~/.gradle.wrapper
        key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt')}}
        restore-key: |
          ${{runner.os}}-gradle-
      
    - name: Build with Gradle
      run: ./gradlew build -i

    - name: Bitgouel Android CI Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: ✅ Bitgouel-Android-CI 성공! ✅
        webhook: ${{ secrets.BITGOUEL_DISCORD_WEBHOOK }}
        color: 65280

    - name: Bitgouel Android CI Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: ❗️ Bitgouel-Android-CI 실패! ❗️
        webhook: ${{ secrets.BITGOUEL_DISCORD_WEBHOOK }}
        color: 16711680
